### ISSUE TITLE
所有接口报502错误

### ISSUE THREAD

**Issue by 272269639** [sanyuan0704/react-cloud-music#56]
貌似是接口的问题，返回信息：
{ code: 502,
 msg: 'Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)' } 
}
TLS相关错误，难道是网易云那边改成https协议了？

**Comment by Jade-Zeng** [comment]
> 貌似是接口的问题，返回信息：
> { code: 502,
> msg: 'Error: read ECONNRESET\n at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)' }
> }
> TLS相关错误，难道是网易云那边改成https协议了？

按照redeme里面的步骤拉项目和安装依赖，先执行start:server命令起api的服务，再执行start跑项目就可以了。

**Comment by sanyuan0704** [comment]
接口没问题啊，线上项目地址&nbsp;http://47.98.159.95:8010/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sanyuan0704/react-cloud-music"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 下午5:39
收件人:&nbsp;"sanyuan0704/react-cloud-music"<react-cloud-music@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [sanyuan0704/react-cloud-music] 所有接口报502错误 (#56)





  
貌似是接口的问题，返回信息：
 { code: 502,
 msg: 'Error: read ECONNRESET\n at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)' }
 }
 TLS相关错误，难道是网易云那边改成https协议了？
  
按照redeme里面的步骤拉项目和安装依赖，先执行start:server命令起api的服务，再执行start跑项目就可以了。
